//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.01 at 08:39:48 PM GMT 
//


package com.academyproject.championsacademyleague.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ID_GuildMaster_FK" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID_Guild_FK" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID_Warrior_FK" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "GuildPlayersIn", namespace = "http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/GuildPlayers/Schema.xsd")
public class GuildPlayersIn {

    @XmlAttribute(name = "ID_GuildMaster_FK")
    protected String idGuildMasterFK;
    @XmlAttribute(name = "ID_Guild_FK")
    protected String idGuildFK;
    @XmlAttribute(name = "ID_Warrior_FK")
    protected String idWarriorFK;

    /**
     * Gets the value of the idGuildMasterFK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDGuildMasterFK() {
        return idGuildMasterFK;
    }

    /**
     * Sets the value of the idGuildMasterFK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDGuildMasterFK(String value) {
        this.idGuildMasterFK = value;
    }

    /**
     * Gets the value of the idGuildFK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDGuildFK() {
        return idGuildFK;
    }

    /**
     * Sets the value of the idGuildFK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDGuildFK(String value) {
        this.idGuildFK = value;
    }

    /**
     * Gets the value of the idWarriorFK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDWarriorFK() {
        return idWarriorFK;
    }

    /**
     * Sets the value of the idWarriorFK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDWarriorFK(String value) {
        this.idWarriorFK = value;
    }

}
