//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 11:02:52 AM GMT 
//


package com.academyproject.championsacademyleague.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/NotificationReceivers/Schema.xsd}NotificationReceiversOut"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notificationReceiversOut"
})
@XmlRootElement(name = "NotificationReceiversDataOutput", namespace = "http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/NotificationReceivers/Schema.xsd")
public class NotificationReceiversDataOutput {

    @XmlElement(name = "NotificationReceiversOut", namespace = "http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/NotificationReceivers/Schema.xsd")
    protected List<NotificationReceiversOut> notificationReceiversOut;

    public NotificationReceiversDataOutput(){}

    public NotificationReceiversDataOutput(List<NotificationReceiversOut> notificationReceiversOut){
        this.notificationReceiversOut=notificationReceiversOut;
    }

    /**
     * Gets the value of the notificationReceiversOut property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationReceiversOut }
     *     
     */
    public List<NotificationReceiversOut> getNotificationReceiversOut() {
        if(notificationReceiversOut==null){
            notificationReceiversOut=new ArrayList<NotificationReceiversOut>();
        }
        return notificationReceiversOut;
    }

    /**
     * Sets the value of the notificationReceiversOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationReceiversOut }
     *     
     */
    public void setNotificationReceiversOut(List<NotificationReceiversOut> value) {
        this.notificationReceiversOut = value;
    }

}
