//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 11:02:52 AM GMT 
//


package com.academyproject.championsacademyleague.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/NotificationReceivers/Schema.xsd}NotificationReceiversIn"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notificationReceiversIn"
})
@XmlRootElement(name = "NotificationReceiversDataInput", namespace = "http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/NotificationReceivers/Schema.xsd")
public class NotificationReceiversDataInput {

    @XmlElement(name = "NotificationReceiversIn", namespace = "http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/NotificationReceivers/Schema.xsd")
    protected List<NotificationReceiversIn> notificationReceiversIn;

    public  NotificationReceiversDataInput(){}

    public  NotificationReceiversDataInput(List<NotificationReceiversIn> notificationReceiversIn){
        this.notificationReceiversIn=notificationReceiversIn;
    }

    /**
     * Gets the value of the notificationReceiversIn property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationReceiversIn }
     *     
     */
    public List<NotificationReceiversIn> getNotificationReceiversIn() {
        if(notificationReceiversIn==null){
            notificationReceiversIn=new ArrayList<NotificationReceiversIn>();
        }
        return notificationReceiversIn;
    }

    /**
     * Sets the value of the notificationReceiversIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationReceiversIn }
     *     
     */
    public void setNotificationReceiversIn(List<NotificationReceiversIn> value) {
        this.notificationReceiversIn = value;
    }

}
