//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.25 at 05:33:08 PM BST 
//


package com.academyproject.championsacademyleague.schemas;

import com.academyproject.championsacademyleague.schemas.VideoDataInput;
import com.academyproject.championsacademyleague.schemas.VideoDataOutput;
import com.academyproject.championsacademyleague.schemas.VideoInput;
import com.academyproject.championsacademyleague.schemas.VideoOutput;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AttendedEventsDataInput }
     * 
     */
    public AttendedEventsDataInput createAttendedEventsDataInput() {
        return new AttendedEventsDataInput();
    }

    /**
     * Create an instance of {@link AttendedEventsIn }
     * 
     */
    public AttendedEventsIn createAttendedEventsIn() {
        return new AttendedEventsIn();
    }

    /**
     * Create an instance of {@link AttendedEventsDataOutput }
     * 
     */
    public AttendedEventsDataOutput createAttendedEventsDataOutput() {
        return new AttendedEventsDataOutput();
    }

    /**
     * Create an instance of {@link AttendedEventsOut }
     * 
     */
    public AttendedEventsOut createAttendedEventsOut() {
        return new AttendedEventsOut();
    }

    /**
     * Create an instance of {@link ClosetDataInput }
     * 
     */
    public ClosetDataInput createClosetDataInput() {
        return new ClosetDataInput();
    }

    /**
     * Create an instance of {@link ClosetIn }
     * 
     */
    public ClosetIn createClosetIn() {
        return new ClosetIn();
    }

    /**
     * Create an instance of {@link ClosetDataOutput }
     * 
     */
    public ClosetDataOutput createClosetDataOutput() {
        return new ClosetDataOutput();
    }

    /**
     * Create an instance of {@link ClosetOut }
     * 
     */
    public ClosetOut createClosetOut() {
        return new ClosetOut();
    }

    /**
     * Create an instance of {@link EventsDataInput }
     * 
     */
    public EventsDataInput createEventsDataInput() {
        return new EventsDataInput();
    }

    /**
     * Create an instance of {@link EventsIn }
     * 
     */
    public EventsIn createEventsIn() {
        return new EventsIn();
    }

    /**
     * Create an instance of {@link EventsDataOutput }
     * 
     */
    public EventsDataOutput createEventsDataOutput() {
        return new EventsDataOutput();
    }

    /**
     * Create an instance of {@link EventsOut }
     * 
     */
    public EventsOut createEventsOut() {
        return new EventsOut();
    }

    /**
     * Create an instance of {@link GuildEventsDataInput }
     * 
     */
    public GuildEventsDataInput createGuildEventsDataInput() {
        return new GuildEventsDataInput();
    }

    /**
     * Create an instance of {@link GuildEventsIn }
     * 
     */
    public GuildEventsIn createGuildEventsIn() {
        return new GuildEventsIn();
    }

    /**
     * Create an instance of {@link GuildEventsDataOutput }
     * 
     */
    public GuildEventsDataOutput createGuildEventsDataOutput() {
        return new GuildEventsDataOutput();
    }

    /**
     * Create an instance of {@link GuildEventsOut }
     * 
     */
    public GuildEventsOut createGuildEventsOut() {
        return new GuildEventsOut();
    }

    /**
     * Create an instance of {@link GuildDataInput }
     * 
     */
    public GuildDataInput createGuildDataInput() {
        return new GuildDataInput();
    }

    /**
     * Create an instance of {@link GuildIn }
     * 
     */
    public GuildIn createGuildIn() {
        return new GuildIn();
    }

    /**
     * Create an instance of {@link GuildDataOutput }
     * 
     */
    public GuildDataOutput createGuildDataOutput() {
        return new GuildDataOutput();
    }

    /**
     * Create an instance of {@link GuildOut }
     * 
     */
    public GuildOut createGuildOut() {
        return new GuildOut();
    }

    /**
     * Create an instance of {@link PlayerDataInput }
     * 
     */
    public schemas.PlayerDataInput createPlayerDataInput() {
        return new schemas.PlayerDataInput();
    }

    /**
     * Create an instance of {@link PlayerIn }
     * 
     */
    public schemas.PlayerIn createPlayerIn() {
        return new schemas.PlayerIn();
    }

    /**
     * Create an instance of {@link PlayerDataOutput }
     * 
     */
    public schemas.PlayerDataOutput createPlayerDataOutput() {
        return new schemas.PlayerDataOutput();
    }

    /**
     * Create an instance of {@link PlayerOut }
     * 
     */
    public schemas.PlayerOut createPlayerOut() {
        return new schemas.PlayerOut();
    }

    /**
     * Create an instance of {@link RewardsDataInput }
     * 
     */
    public schemas.RewardsDataInput createRewardsDataInput() {
        return new schemas.RewardsDataInput();
    }

    /**
     * Create an instance of {@link RewardsIn }
     * 
     */
    public schemas.RewardsIn createRewardsIn() {
        return new schemas.RewardsIn();
    }

    /**
     * Create an instance of {@link RewardsDataOutput }
     * 
     */
    public schemas.RewardsDataOutput createRewardsDataOutput() {
        return new schemas.RewardsDataOutput();
    }

    /**
     * Create an instance of {@link RewardsOut }
     * 
     */
    public schemas.RewardsOut createRewardsOut() {
        return new schemas.RewardsOut();
    }

    /**
     * Create an instance of {@link SkinDataInput }
     * 
     */
    public schemas.SkinDataInput createSkinDataInput() {
        return new schemas.SkinDataInput();
    }

    /**
     * Create an instance of {@link SkinIn }
     * 
     */
    public schemas.SkinIn createSkinIn() {
        return new schemas.SkinIn();
    }

    /**
     * Create an instance of {@link SkinDataOutput }
     * 
     */
    public schemas.SkinDataOutput createSkinDataOutput() {
        return new schemas.SkinDataOutput();
    }

    /**
     * Create an instance of {@link SkinOut }
     * 
     */
    public schemas.SkinOut createSkinOut() {
        return new schemas.SkinOut();
    }

    /**
     * Create an instance of {@link VideoDataInput }
     * 
     */
    public VideoDataInput createVideoDataInput() {
        return new VideoDataInput();
    }

    /**
     * Create an instance of {@link VideoInput }
     * 
     */
    public VideoInput createVideoInput() {
        return new VideoInput();
    }

    /**
     * Create an instance of {@link VideoDataOutput }
     * 
     */
    public VideoDataOutput createVideoDataOutput() {
        return new VideoDataOutput();
    }

    /**
     * Create an instance of {@link VideoOutput }
     * 
     */
    public VideoOutput createVideoOutput() {
        return new VideoOutput();
    }

    /**
     * Create an instance of {@link WatchedVideosDataInput }
     * 
     */
    public schemas.WatchedVideosDataInput createWatchedVideosDataInput() {
        return new schemas.WatchedVideosDataInput();
    }

    /**
     * Create an instance of {@link WatchedVideosIn }
     * 
     */
    public schemas.WatchedVideosIn createWatchedVideosIn() {
        return new schemas.WatchedVideosIn();
    }

    /**
     * Create an instance of {@link WatchedVideosDataOutput }
     * 
     */
    public schemas.WatchedVideosDataOutput createWatchedVideosDataOutput() {
        return new schemas.WatchedVideosDataOutput();
    }

    /**
     * Create an instance of {@link WatchedVideosOut }
     * 
     */
    public schemas.WatchedVideosOut createWatchedVideosOut() {
        return new schemas.WatchedVideosOut();
    }

}
