//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.25 at 05:33:08 PM BST 
//


package com.academyproject.championsacademyleague.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="ChampiesCost" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ID_Skin" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ImagePath" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="MinXP" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SkinName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="SkinType" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "skinOut", namespace = "http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/Skin/Schema.xsd")
public class SkinOut {

    @XmlAttribute(name = "ChampiesCost")
    protected String champiesCost;
    @XmlAttribute(name = "ID_Skin")
    protected String idSkin;
    @XmlAttribute(name = "ImagePath")
    protected String imagePath;
    @XmlAttribute(name = "MinXP")
    protected String minXP;
    @XmlAttribute(name = "SkinName")
    protected String skinName;
    @XmlAttribute(name = "SkinType")
    protected String skinType;

    public SkinOut() {

    }

    public SkinOut(String idSkin, String skinName, String imagePath, String minXP, String champiesCost, String skinType) {
        this.champiesCost = champiesCost;
        this.idSkin = idSkin;
        this.imagePath = imagePath;
        this.minXP = minXP;
        this.skinName = skinName;
        this.skinType = skinType;
    }

    /**
     * Gets the value of the champiesCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChampiesCost() {
        return champiesCost;
    }

    /**
     * Sets the value of the champiesCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChampiesCost(String value) {
        this.champiesCost = value;
    }

    /**
     * Gets the value of the idSkin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDSkin() {
        return idSkin;
    }

    /**
     * Sets the value of the idSkin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDSkin(String value) {
        this.idSkin = value;
    }

    /**
     * Gets the value of the imagePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * Sets the value of the imagePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagePath(String value) {
        this.imagePath = value;
    }

    /**
     * Gets the value of the minXP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinXP() {
        return minXP;
    }

    /**
     * Sets the value of the minXP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinXP(String value) {
        this.minXP = value;
    }

    /**
     * Gets the value of the skinName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkinName() {
        return skinName;
    }

    /**
     * Sets the value of the skinName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkinName(String value) {
        this.skinName = value;
    }

    /**
     * Gets the value of the skinType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkinType() {
        return skinType;
    }

    /**
     * Sets the value of the skinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkinType(String value) {
        this.skinType = value;
    }

}
