//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 12:21:10 PM GMT 
//


package schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.tibco.com/schemas/TheChampionsAcademyLeague/Service/NotificationReceivers/Schema.xsd}NotificationReceiversOut"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notificationReceiversOut"
})
@XmlRootElement(name = "NotificationReceiversDataOutput")
public class NotificationReceiversDataOutput {

    @XmlElement(name = "NotificationReceiversOut", required = true)
    protected NotificationReceiversOut notificationReceiversOut;

    /**
     * Gets the value of the notificationReceiversOut property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationReceiversOut }
     *     
     */
    public NotificationReceiversOut getNotificationReceiversOut() {
        return notificationReceiversOut;
    }

    /**
     * Sets the value of the notificationReceiversOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationReceiversOut }
     *     
     */
    public void setNotificationReceiversOut(NotificationReceiversOut value) {
        this.notificationReceiversOut = value;
    }

}
